---
- name: copy certificates
  copy:
    src: server.crt
    dest: /etc/ssl/server.crt

- name: copy private key
  copy:
    src: server.key
    dest: /etc/ssl/server.key

- name: copy config
  copy:
    src: angie.conf
    dest: /etc/angie/http.d/default.conf
  notify:
    - "Reload angie"

