---
  - name: install apache2
    apt: 
      name: 
        - apache2
      state: present
      update_cache: true
  
  - name: enable and start service
    service:
      name: apache2
      state: started
      enabled: true
 
  - name: install php
    apt: 
      name: 
        - php8.2
        - php8.2-cli
        - php8.2-common
        - php8.2-imap
        - php8.2-redis
        - php8.2-snmp
        - php8.2-xml
        - php8.2-mysqli
        - php8.2-zip
        - php8.2-mbstring
        - php8.2-curl
        - libapache2-mod-php
      state: present
      update_cache: true
